Fix the `determination-ardour-export` file extension regex

diff --git a/stuff/bin/determination-ardour-export b/stuff/bin/determination-ardour-export
--- a/stuff/bin/determination-ardour-export
+++ b/stuff/bin/determination-ardour-export
@@ -46,7 +46,7 @@ while [[ "$#" -gt 0 ]]; do
 done
 
 if [[ -z "$input" ]]; then usage; exit 1; fi
-if [[ ! "$input" =~ .*\\.ardour ]]; then >&2 echo 'Error: Input file extension must be .ardour'; exit 1; fi
+if [[ ! "$input" =~ .*\.ardour ]]; then >&2 echo 'Error: Input file extension must be .ardour'; exit 1; fi
 project="$(dirname "$input")"
 session="$(basename "$input" .ardour)"
 
